---@module 'luassert'

local config = require("gh-review.config")

describe("config", function()
  before_each(function()
    config.setup()
  end)

  describe("defaults", function()
    it("has all expected keymap fields", function()
      local km = config.get().keymaps
      assert.is_not_nil(km.prefix)
      assert.is_not_nil(km.checkout)
      assert.is_not_nil(km.review_current)
      assert.is_not_nil(km.files)
      assert.is_not_nil(km.comments)
      assert.is_not_nil(km.reply)
      assert.is_not_nil(km.new_thread)
      assert.is_not_nil(km.toggle_resolve)
      assert.is_not_nil(km.hover)
      assert.is_not_nil(km.description)
      assert.is_not_nil(km.refresh)
      assert.is_not_nil(km.close)
      assert.is_not_nil(km.next_comment)
      assert.is_not_nil(km.prev_comment)
      assert.is_not_nil(km.next_diff)
      assert.is_not_nil(km.prev_diff)
    end)

    it("includes toggle_overlay keymap", function()
      assert.are.equal("D", config.get().keymaps.toggle_overlay)
    end)

    it("includes open_minidiff keymap", function()
      assert.are.equal("e", config.get().keymaps.open_minidiff)
    end)
  end)

  describe("setup", function()
    it("deep merges user config", function()
      config.setup({ keymaps = { toggle_overlay = "X" } })
      local km = config.get().keymaps
      assert.are.equal("X", km.toggle_overlay)
      -- Other defaults preserved
      assert.are.equal("<leader>gp", km.prefix)
      assert.are.equal("e", km.open_minidiff)
    end)

    it("preserves defaults when no user config", function()
      config.setup()
      assert.are.equal("gh", config.get().gh_cmd)
      assert.are.equal("rounded", config.get().float.border)
    end)

    it("partial keymap override merges with defaults", function()
      config.setup({ keymaps = { checkout = "x", reply = "R" } })
      local km = config.get().keymaps
      assert.are.equal("x", km.checkout)
      assert.are.equal("R", km.reply)
      -- All other defaults preserved
      assert.are.equal("<leader>gp", km.prefix)
      assert.are.equal("f", km.files)
      assert.are.equal("c", km.comments)
      assert.are.equal("n", km.new_thread)
      assert.are.equal("t", km.toggle_resolve)
      assert.are.equal("v", km.hover)
      assert.are.equal("d", km.description)
      assert.are.equal("D", km.toggle_overlay)
      assert.are.equal("e", km.open_minidiff)
      assert.are.equal("O", km.review_current)
      assert.are.equal("R", km.refresh)
      assert.are.equal("q", km.close)
      assert.are.equal("]c", km.next_comment)
      assert.are.equal("[c", km.prev_comment)
      assert.are.equal("C", km.commits)
    end)

    it("icon override merges correctly", function()
      config.setup({ icons = { added = "+", deleted = "-" } })
      local icons = config.get().icons
      assert.are.equal("+", icons.added)
      assert.are.equal("-", icons.deleted)
      -- Defaults preserved
      assert.are.equal("M", icons.modified)
      assert.are.equal("R", icons.renamed)
      assert.are.equal("✓", icons.approved)
      assert.are.equal("✗", icons.changes_requested)
      assert.are.equal("◔", icons.review_required)
      assert.are.equal("⎇", icons.branch)
    end)

    it("float override merges correctly", function()
      config.setup({ float = { border = "single" } })
      local fl = config.get().float
      assert.are.equal("single", fl.border)
      assert.are.equal(100, fl.max_width)
      assert.are.equal(30, fl.max_height)
    end)

    it("unknown keys are preserved (forward-compat)", function()
      config.setup({ custom_option = "hello", keymaps = { custom_key = "Z" } })
      assert.are.equal("hello", config.get().custom_option)
      assert.are.equal("Z", config.get().keymaps.custom_key)
    end)
  end)
end)
